# Generated by Django 3.2.6 on 2021-08-27 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('name', 'Full name!'), ('job', 'Job'), ('email', 'Email'), ('domain_name', 'Domain name'), ('phone_number', 'Phone number'), ('company', 'Company name'), ('sentences (nb = 3)', 'Text!'), ('random_int(min=0, max=15)', 'Integer!'), ('address', 'Address'), ('date(pattern="%d-%m-%Y", end_datetime=datetime.date(2000, 1, 1))', 'Date')], max_length=128)),
                ('order', models.PositiveIntegerField()),
                ('data_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='challenge.dataschema')),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='')),
                ('count', models.PositiveIntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('data_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.dataschema')),
            ],
        ),
    ]
