# Generated by Django 3.2.6 on 2021-08-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemafield',
            name='type',
            field=models.CharField(choices=[('fake.name', 'Full name!'), ('fake.job', 'Job'), ('fake.email', 'Email'), ('fake.domain_name', 'Domain name'), ('fake.phone_number', 'Phone number'), ('fake.company', 'Company name'), ('fake.sentences (nb = 3)', 'Text!'), ('fake.random_int(min=0, max=15)', 'Integer!'), ('fake.address', 'Address'), ('fake.date(pattern="%d-%m-%Y"', 'Date')], max_length=128),
        ),
    ]
